-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Aug 24, 2014 at 01:37 PM
-- Server version: 5.5.37-0ubuntu0.14.04.1
-- PHP Version: 5.5.9-1ubuntu4.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `mymadrasa`
--

-- --------------------------------------------------------

--
-- Table structure for table `post`
--

CREATE TABLE IF NOT EXISTS `post` (
  `ID` int(3) DEFAULT NULL,
  `title` varchar(65) DEFAULT NULL,
  `link` varchar(117) DEFAULT NULL,
  `image` varchar(144) DEFAULT NULL,
  `description` varchar(155) DEFAULT NULL,
  `tags` varchar(31) DEFAULT NULL,
  `type` varchar(5) DEFAULT NULL,
  `category` varchar(9) DEFAULT NULL,
  `clicks` int(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `post`
--

INSERT INTO `post` (`ID`, `title`, `link`, `image`, `description`, `tags`, `type`, `category`, `clicks`) VALUES
(1, 'Marilyn Portrait Tutorial', 'http://www.stars-portraits.com/en/tutorial/marilyn.html', 'http://www.stars-portraits.com/img/tutoriaux/marilyn.jpg', 'A truly fantastic drawing tutorial to learn how to draw a portrait of Marilyn Monroe with pencil.', 'StarsPortraits Art Monroe', 'text', 'art', 0),
(2, 'The Easiest Way to Turn Business Cards Into Digital Contacts', 'https://www.themuse.com/advice/the-quickest-easiest-way-to-turn-business-cards-into-digital-contacts', 'https://tm-pilbox.global.ssl.fastly.net/?url=https%3A%2F%2Ftm-prod.global.ssl.fastly.net%2Fuploaded%2Fattachments%2F14497.jpg%3Fv%3D74df11&h=367', 'Even in our hyper-connected world, business cards are an important networking tool.', 'TheMuse Career Networking', 'text', 'career', 0),
(3, 'Think Design: History', 'http://www.makeshapechange.com/think-design/history', 'http://www.makeshapechange.com/images/uploads/Sequence_A_v04_500.gif', 'Before our film even begins we get a whirlwind history of design.', 'ThinkDesign Design History', 'text', 'design', 0),
(4, 'Think Design: Homes', 'http://www.makeshapechange.com/think-design/homes', 'http://www.makeshapechange.com/images/uploads/Sequence_B_v01.gif', 'All houses (well with some exceptions) have walls, a roof, doors and windows, but they aren''t all the same.', 'ThinkDesign Design Homes', 'text', 'design', 0),
(5, 'Think Design: Information', 'http://www.makeshapechange.com/think-design/information', 'http://www.makeshapechange.com/images/uploads/Sequence_F_new2.gif', 'A lot of good design is almost invisible. This is particularly true in the design of information.', 'ThinkDesign Design Information', 'text', 'design', 0),
(6, 'Think Design: Spaces', 'http://www.makeshapechange.com/think-design/spaces', 'http://www.makeshapechange.com/images/uploads/Sequence_G_newSB2.gif', 'Each space has a particular job to do and is filled with things to help do that job.', 'ThinkDesign Design Spaces', 'text', 'design', 0),
(7, 'Think Design: Experiences', 'http://www.makeshapechange.com/think-design/experiences', 'http://www.makeshapechange.com/images/uploads/Sequence_I_newSB3.gif', 'New experiences usually feature many kinds of design together and work across real life and different kinds of technology.', 'ThinkDesign Design Experiences', 'text', 'design', 0),
(8, 'Think Design: Objects', 'http://www.makeshapechange.com/think-design/objects', 'http://www.makeshapechange.com/images/uploads/sequence_k_500_v02_jknew.gif', 'Our modern lives are packed full of objects, ones we notice and ones we don''t, all of them designed.', 'ThinkDesign Design Objects', 'text', 'design', 0),
(9, 'Think Design: Communications', 'http://www.makeshapechange.com/think-design/communications', 'http://www.makeshapechange.com/images/uploads/Sequence_M_v01.gif', 'People have used design to help us communicate for thousands of years.', 'ThinkDesign Design Communicate', 'text', 'design', 0),
(10, 'Think Design: Technology', 'http://www.makeshapechange.com/think-design/technology', 'http://www.makeshapechange.com/images/uploads/Sequence_H_newSB3.gif', 'Technology and design have always gone hand in hand.', 'ThinkDesign Design Technology', 'text', 'design', 0),
(11, 'Think Design: Communities', 'http://www.makeshapechange.com/think-design/communities', 'http://www.makeshapechange.com/images/uploads/Sequence_Q_v01.gif', 'What would you consider to be part of your community?', 'ThinkDesign Design Communities', 'text', 'design', 0),
(12, 'Intro to Cinema 4D', 'http://greyscalegorilla.com/blog/tutorials/cinema-4d-basics/', 'http://greyscalegorilla.com/blog/wp-content/uploads/thumbnails/1904.jpg', 'Today, I run through the basics of setting up a scene in Cinema 4D and rendering an image.', 'GreyScaleGorilla Design C4D', 'video', 'design', 0),
(13, 'Hello World', 'https://hackdesign.org/lessons/0', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week0-3f0b161389cda67d9a2b726fafa1dbb5.png', 'This film is absolutely crucial to setting the groundwork for you in this course.', 'HackDesign Design Objectified', 'text', 'design', 0),
(14, 'What is design? Why is it important?', 'https://hackdesign.org/lessons/1', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week1-282555cc810bd5d2799940e06c83dcd0.png', 'As you read through the tips, notice that they&#039;re not necessarily only about design &dash; they&#039re about making great products in general.', 'HackDesign Design Tips', 'text', 'design', 0),
(15, 'Dive Into Typography', 'https://hackdesign.org/lessons/2', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week2-2a77f2b05a2c22973405d37a66ca7cf4.png', 'Try to learn why this iconic typeface is so prevalent in our world, and how it grew to ubiquity.', 'HackDesign Design Typography', 'text', 'design', 0),
(16, 'The Amazing New Mobile Web', 'https://hackdesign.org/lessons/3', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week3-3d69b6a1ba8a3871d68f0df53e7cb48c.png', 'This post covers some technical aspects of mobile web design with some general theory and guidelines.', 'HackDesign Design Mobile Web', 'text', 'design', 0),
(17, 'Know Your Tools', 'https://hackdesign.org/lessons/4', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week4-57f3fb526f5f24cad726481a3f37f8a0.png', 'Reda Lemeden&#039;s brilliant Smashing Magazine article covers the background and available techniques when designing for the web.', 'HackDesign Design Tools', 'text', 'design', 0),
(18, 'Typography in Product Design', 'https://hackdesign.org/lessons/5', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week5-c067d1e511e5098dc348507930805de0.png', 'This article is extremely short, but it contains a valuable message.', 'HackDesign Design Product', 'text', 'design', 0),
(19, 'Exploring the World of Typefaces', 'https://hackdesign.org/lessons/6', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week6-45e9dd1f841cff74e15559b582a98575.png', 'When we look back at black and white movies, we marvel at the results they could achieve without color.', 'HackDesign Design Typefaces', 'text', 'design', 0),
(20, 'Responsive Typography In Action', 'https://hackdesign.org/lessons/7', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week7-c79819c8d92563e11757edb6fb46668c.png', 'Two weeks ago, Jared got us experimenting with typefaces on Typecast. Let&#039;s try something different this week.', 'HackDesign Design Responsive', 'text', 'design', 0),
(21, 'Typography in Practice, and Where to Go from Here', 'https://hackdesign.org/lessons/8', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week8-deed7077da5cc5fa57182fc4e2f95f46.png', 'If I read Robert Bringhurst&#039;s Elements of Typographic Style, I would not need to attend any of his classes.', 'HackDesign Design Typography', 'text', 'design', 0),
(22, 'An Introduction to User Experience Design', 'https://hackdesign.org/lessons/9', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week9-dc3ad7646b3070a96d211fe0326a7158.png', 'Donald Norman is often called the inventor of User Experience, and this review covers many important points from his seminal book.', 'HackDesign Design UX', 'text', 'design', 0),
(23, 'Rapid Prototyping Tools & Best Practices', 'https://hackdesign.org/lessons/10', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week10-b33042f4edc2fd03ab5801a311a37946.png', 'There are TONS of prototyping tools. These are some of my favorites.', 'HackDesign Design Tools', 'text', 'design', 0),
(24, 'Defining & Expanding User Experience', 'https://hackdesign.org/lessons/11', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week11-c067d1e511e5098dc348507930805de0.png', 'Using paper, a whiteboard or sticky note map out a common checkout flow. Look upon the flow and find ways for this same flow to be easier.', 'HackDesign Design UX', 'text', 'design', 0),
(25, 'Understanding the User in User Experience', 'https://hackdesign.org/lessons/12', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week12-3d69b6a1ba8a3871d68f0df53e7cb48c.png', 'If you&#039;re ever unsure about whether your product, new feature, or line of copy makes sense, you can always do a quick reality check with your users.', 'HackDesign Design UX', 'text', 'design', 0),
(26, 'Vector Interface Design', 'https://hackdesign.org/lessons/13', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week13-47741ef5f83ce217ae66e14a1ccec4f8.png', 'User Interface design plays a very important role as the translator in the communication between the user and the app&#039;s back-end.', 'HackDesign Design Vector', 'text', 'design', 0),
(27, 'The Medium and Mechanics of Iconography', 'https://hackdesign.org/lessons/14', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week14-67bc456b99906e8aece11979d9781a59.png', 'Iconography can also be an efficient way to communicate a concept in a small amount of space, which is increasingly important.', 'HackDesign Design Icon', 'text', 'design', 0),
(28, 'Making the content flow: introducing responsive web design', 'https://hackdesign.org/lessons/15', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week15-3d69b6a1ba8a3871d68f0df53e7cb48c.png', 'Remember that as much as these are standalone elements, they do exist in surroundings of others &dash; keep the interactive nature in mind.', 'HackDesign Design Responsive', 'text', 'design', 0),
(29, 'UI Design with Purpose', 'https://hackdesign.org/lessons/16', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week16-1f3144a77e02ef4d46d90681bfea8b27.png', 'Who Owns Your UX Philosophy? Great UI is fueled and informed by great UX.', 'HackDesign Design UI', 'text', 'design', 0),
(30, 'Building Color Confidence', 'https://hackdesign.org/lessons/17', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week17-956adf0e457dfcfa505a2b2496b9b2be.png', 'Being fluent in color vocabulary will help you notice the subtleties and awaken your color instinct.', 'HackDesign Design Color', 'text', 'design', 0),
(31, 'White Space: Designing the Invisible', 'https://hackdesign.org/lessons/18', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week18-0b3976fda9c5675f82cd0b8ef30ef32d.png', 'No matter what visual style is hot, no matter what great product you''re using, every piece of good design uses white space well.', 'HackDesign Design WhiteSpace', 'text', 'design', 0),
(32, 'Achieving Visual Hierarchy', 'https://hackdesign.org/lessons/19', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week19-c067d1e511e5098dc348507930805de0.png', 'Read the article and think about the author''s hierarchist&#039;s toolbox, and add to the list of ways you can visually set things apart.', 'HackDesign Design Hierarchy', 'text', 'design', 0),
(33, 'Deciding What&#039;s Good: Design Principles', 'https://hackdesign.org/lessons/20', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week20-2642fdb7a2d175870c55923bee919411.png', 'Design is by nature a subjective thing. So how do you decide what good is for your product?', 'HackDesign Design Principles', 'text', 'design', 0),
(34, 'Designing your first iPhone App', 'https://hackdesign.org/lessons/21', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week21-961f02ef0def258a96194746d5748e0d.png', 'Now using what you&#039;ve learned from the articles you&#039;ve just read, see how you can improve on some the techniques suggested in this tutorial.', 'HackDesign Design Mobile', 'text', 'design', 0),
(35, 'Designing for Mobile Web', 'https://hackdesign.org/lessons/22', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week22-7c673df46c42343a68b90c371d75724a.png', 'Browse this breakdown of different mobile layout patterns to see if you can identify which of these you''ve seen in the wild.', 'HackDesign Design Mobile', 'text', 'design', 0),
(36, 'Mobile App Analytics Is Not That Special', 'https://hackdesign.org/lessons/23', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week23-8d5d31fa5ca48fd93273b6e0ee5182e8.png', 'Startup Metrics for Pirates: AARRR! How can you use the AARRR concept within your mobile app?', 'HackDesign Analytics AARRR', 'text', 'design', 0),
(37, 'Using Icons in Interfaces', 'https://hackdesign.org/lessons/24', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week24-f3342d4c5287b6f3cecd84b3bcc2c73f.png', 'Sketch an iPhone-style tab bar navigation with icons and labels. Consider the meaning of the icons as well as the language used for labels.', 'HackDesign Design UI', 'text', 'design', 0),
(38, 'Power to the People &dash; Mastering Human-Centered Design', '', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week25-63394c6d85160dedd19689243bb06a95.png', 'Watch this talk by Wilson Miner and take the time to step back and consider not just your product and its users, but the context they exist within.', 'HackDesign Design User-Centered', 'text', 'design', 0),
(39, 'Content Strategy for Interfaces', 'https://hackdesign.org/lessons/26', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week26-e09396d9915abdfde9b6dc95153a4622.png', 'Open a document and create two columns. In the first column, list all the main types of content in your product.', 'HackDesign Design Content', 'text', 'design', 0),
(40, 'Creative problem solving and everyday design', 'https://hackdesign.org/lessons/27', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week27-fbaac573a1bf24d5f4d732e4d65397c6.png', 'Design is about an open and inspired way of working. It&#039;s about solving problems, and that&#039;s applicable to anyone.', 'HackDesign Design Creative', 'text', 'design', 0),
(41, 'Effective Behavior Design', 'https://hackdesign.org/lessons/28', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week28-aa60010dca60dd95207d1080182703f8.png', 'Part of designing a user experience is convincing the user to behave a certain way in order to reach a specific outcome.', 'HackDesign Design Behavior', 'text', 'design', 0),
(42, 'Cultivating Compassion', 'https://hackdesign.org/lessons/29', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week29-13a5e15b021664f2b62d0186fa1267d8.png', 'Read this article in the NY Times about how technology is making us less present.', 'HackDesign Design Empathy', 'text', 'design', 0),
(43, 'Designing with Code', 'https://hackdesign.org/lessons/30', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week30-503484ed6be1ac49ff3356114f73593e.png', 'Make sure to download the Emmet plugin for your favorite text editor, which will allow you to write HTML and CSS at lightning speeds.', 'HackDesign Design Code', 'text', 'design', 0),
(44, 'It&#039;s All Just Systems Design', 'https://hackdesign.org/lessons/31', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week31-7f316ad52b750c8d788a5f4d6fb6c29f.png', 'As someone who designs and codes, I find new similarities between visual design and programming every day.', 'HackDesign Design Systems', 'text', 'design', 0),
(45, 'Designing with Grids', 'https://hackdesign.org/lessons/32', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week32-c67cddaf16f6a97aae5b9806b9a4bf58.png', 'The human brain has a penchant for identifying patterns, decoding them, then recoding them for later reuse.', 'HackDesign Design Grids', 'text', 'design', 0),
(46, 'Designing Quality Products', 'https://hackdesign.org/lessons/34', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week34-704b416bbf24346009ca7de96043ed65.png', 'Great products begin and end with great design. Design should influence all product decisions.', 'HackDesign Design Product', 'text', 'design', 0),
(47, 'The Little Things Matter', 'https://hackdesign.org/lessons/35', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week35-e55011abdf0bb564c6bb10f338b13492.png', 'How can you show, not tell, your users about your product?', 'HackDesign Design Details', 'text', 'design', 0),
(48, 'Designing Habit&dash;Forming Products', 'https://hackdesign.org/lessons/36', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week36-b5ec41a3ee923c128887eb2f0c81c883.png', 'MIT professor Jesse Schell, argues that new behaviors must be things people wanna do, not hafta do.', 'HackDesign Design Behavior', 'text', 'design', 0),
(49, 'A Holistic Guide to Product Design', 'https://hackdesign.org/lessons/37', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week37-8eef49e83cf7c77610d7ee0ddbdd47aa.png', 'Read this article and think about how you could build delight into your product from day one.', 'HackDesign Design Holistic', 'text', 'design', 0),
(50, 'Animation, Direct Manipulation & Feedback', 'https://hackdesign.org/lessons/38', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week38-6c5850bac87f877cd4f76e78951948ff.png', 'Bret Victor demonstrates an interface which uses direct manipulation to draw dynamic visualizations.', 'HackDesign Design Animation', 'text', 'design', 0),
(51, 'The Human Element', 'https://hackdesign.org/lessons/39', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week39-359540e16859fa5ea07e3777cc397b36.png', 'LayerVault creates a proficiency profile for every user.', 'HackDesign Design Human', 'text', 'design', 0),
(52, 'Pushing prototypes with Quartz Composer', 'https://hackdesign.org/lessons/40', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week40-73e43c7b81807e04d56de1b6d640bbf5.png', 'VJ&#039;s and visual effects artists are the ones who really know QC and are able to bend it to do whatever they desire.', 'HackDesign Design Protoypes', 'text', 'design', 0),
(53, 'Prototyping Advanced Mobile Interactions with Framer', 'https://hackdesign.org/lessons/41', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week41-81fa25daf5264aca41ae4b0ed8deb133.png', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week41-81fa25daf5264aca41ae4b0ed8deb133.png', 'HackDesign Design Protoypes', 'text', 'design', 0),
(54, 'The All Encompassing User Experience', 'https://hackdesign.org/lessons/42', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week42-a3e80024c7bfdc8e86a33be47cc007f4.png', 'Fortunately, companies like AirBnb and Square are taking initiative and showing other companies how it&#039;s done.', 'HackDesign Design UX', 'text', 'design', 0),
(55, 'Designing With Your Ears', 'https://hackdesign.org/lessons/43', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week43-5769f34d8df0b4ecb363c722bae210ae.png', 'Listen to the presentation while watching the slides. Create personas representing the different types of people who have interviewed.', 'HackDesign Design Feedback', 'text', 'design', 0),
(56, 'Win The Internet With A/B Testing', 'https://hackdesign.org/lessons/44', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week44-7d9020b6a7d2fa71361cf7231db0bc53.png', 'In this article, Kyle mentions quite a few important notes about testing.', 'HackDesign Design A/B Testing', 'test', 'design', 0),
(57, 'Design Your Mobile App For Multiple Platforms', 'https://hackdesign.org/lessons/45', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week45-b7f18ab7e6b6602b17874dbad46ac4f2.png', 'These days it has become commonplace, if not necessary, for mobile apps to be designed across multiple platforms.', 'HackDesign Design App', 'test', 'design', 0),
(58, 'Kickstarting Your Design Career', 'https://hackdesign.org/lessons/46', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week46-0e36b750eb309c9260144e8ae4c1ac79.png', 'Familiarizing yourself with the basics of successful freelancing will help you become knowledgeable in other aspects of the business.', 'HackDesign Design Career', 'test', 'design', 0),
(59, 'How To Get Your First Design Job With No Experience', 'https://hackdesign.org/lessons/47', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week47-4b51942a6bc8f0a961049987f373e384.png', 'It was so articulate, moving, and useful that he asked the designer how he pulled it together. The secret?', 'HackDesign Design Career', 'test', 'design', 0),
(60, 'Why Design?', 'https://hackdesign.org/lessons/48', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week48-7bf9b9d65a1c8fbf7989b26c709465f0.png', 'Watch Frank Chimero, author of The Shape of Design, reflect on how to think about design.', 'HackDesign Design Theory', 'text', 'design', 0),
(61, 'Vim as a Design Tool', 'https://hackdesign.org/lessons/49', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week49-df61c2d937e780495e5956caa1b41331.png', 'This article introduces some basic concepts of command-based editing and how it might help you design better products over time.', 'HackDesign Design Vim', 'text', 'design', 0),
(62, 'A field guide to being better at design by being self aware', 'https://hackdesign.org/lessons/50', 'https://hackdesign.a.ssl.fastly.net/assets/lessons/week50-6ea8ac61bb79004dce50ac961b012678.png', 'Frank Chimero explores the process of design and thereby manages to pose a few important questions that we have all asked at some point in our careers.', 'HackDesign Design Details', 'text', 'design', 0),
(63, 'Plastic Bottle Mosquito Trap', 'http://www.instructables.com/id/Plastic-Bottle-Mosquito-Trap/', 'http://cdn.instructables.com/FGK/06CO/HWLCXJRP/FGK06COHWLCXJRP.LARGE.jpg', 'In this Instructable, I want to show you an all natural and potentially free way to create an efficent mosquito trap with little more than a plastic bottle', 'Instructables diy', 'text', 'diy', 0),
(64, '9 Subtle Ways To Look Sexy', 'http://www.whowhatwear.com/how-to-look-subtly-sexy-2014', 'http://www.whowhatwear.com/img/uploads/current/images/0/81/868/main.original.585x0.jpg', 'Click through now to add just a hint of seduction to your look.', 'WhoWhatWear Fashion Style', 'text', 'fashion', 0),
(65, '13 Ultra-Flattering Pieces To Conceal Your Mid-Section', 'http://www.whowhatwear.com/how-to-dress-hide-stomach-mid-section-2014', 'http://www.whowhatwear.com/img/uploads/current/images/0/81/177/main.original.585x0.jpg', 'Click through to check out the pieces that will make the very most of your gorgeous figure, supermodel abs or not.', 'WhoWhatWear Fashion Style', 'text', 'fashion', 0),
(66, '9 Foolproof Warm-Weather Outfit Formulas To Copy Now', 'http://www.whowhatwear.com/spring-outfit-ideas-formulas-2014', 'http://www.whowhatwear.com/img/uploads/current/images/0/80/657/main.original.585x0.jpg', 'Click thorough the check out the simple equations guaranteed to give you outfit perfection.', 'WhoWhatWear Fashion Spring', 'text', 'fashion', 0),
(67, 'The Style Tips We Learned From Our Moms', 'http://www.whowhatwear.com/style-tips-from-mom-fashion-2014', 'http://www.whowhatwear.com/img/uploads/current/images/0/80/559/main.original.585x0.jpg', 'Click through to see what the ladies around the office learned from their moms.', 'WhoWhatWear Fashion Style', 'text', 'fashion', 0),
(68, '9 Celeb-Inspired Ways To Wear A White Dress This Spring', 'http://www.whowhatwear.com/ways-to-wear-white-dress-spring-summer-2014', 'http://www.whowhatwear.com/img/uploads/current/images/0/80/434/main.original.585x0.jpg', 'To keep this wardrobe essential feeling fresh well through the summer months, take note of these nine foolproof outfit ideas.', 'WhoWhatWear Fashion Style', 'text', 'fashion', 0),
(69, '20 Killer Cooking Hacks To Make You Look Like A Total Pro', 'http://www.lifehack.org/articles/lifestyle/killer-cooking-hacks-thatll-make-you-look-like-total-pro.html', 'http://cdn-media-2.lifehack.org/wp-content/files/2014/06/kitchen-69605_1280.jpg', 'Enjoy cooking again with some of these creative hacks that put a little spice into your dishes and pantry.', 'LifeHack Cooking Food', 'text', 'food', 0),
(70, '10 Tasty and Healthy Kale Recipes You Shouldn&#039;t Miss', 'http://www.lifehack.org/articles/lifestyle/tasty-and-healthy-kale-recipes-you-shouldnt-miss.html', 'http://cdn-media-1.lifehack.org/wp-content/files/2014/06/kale-247026_1280.jpg', 'More and more people are trying to incorporate this deep green leaf into their everyday eating.', 'LifeHack Food Cooking', 'text', 'food', 0),
(71, 'leydavak&#039;s Grazioso Silicone Onlays Wedding Cake Tutorial', 'http://cakecentral.com/b/tutorial/leydavak-grazioso-cake-tutorial-onlay', 'http://media-us-148799954183.s3.amazonaws.com/b/wp-content/blogs.dir/1/files/2014/07/leyda-silicone-onlay_tutorial-600x450.jpg', 'Leyda Vakarelov shows you how to decorate an Onlays wedding cake.', 'CakeCentral Food Cakes', 'text', 'food', 0),
(72, 'Life Hack #1515: Silence', 'http://1000lifehacks.com/post/91385656039', 'http://33.media.tumblr.com/42d02f17f4087f5807b8a2771056fc90/tumblr_n8iejyUA3z1sa4vz3o1_500.png', 'Sometimes it&#039;s best to keep quiet.', '1000LifeHacks Lifehacks', 'image', 'lifehacks', 0),
(73, 'Life Hack #1513: Batteries', 'http://1000lifehacks.com/post/91302364948', 'http://38.media.tumblr.com/6d43d5ca0b394ed6421a338ad7b52d46/tumblr_n8gfkqYo991sa4vz3o1_500.png', 'Drop a battery to see if it''s good.', '1000LifeHacks Lifehacks', 'image', 'lifehacks', 0),
(74, 'Life Hack #1512: Hiccups', 'http://1000lifehacks.com/post/91284634542', 'http://38.media.tumblr.com/959e43d4cb4b141744a0e04e1166d31c/tumblr_n8gfkpFTx81sa4vz3o1_500.png', 'Getting rid of hiccups.', '1000Lifehacks Lifehacks', 'image', 'lifehacks', 0),
(75, 'Life Hack #1511: American Quarters', 'http://1000lifehacks.com/post/91267000974', 'http://31.media.tumblr.com/0da9115957417e54e86d8c56059b9795/tumblr_n8gfknQxnc1sa4vz3o1_500.png', 'The value of American quarters.', '1000LifeHacks Lifehacks', 'image', 'lifehacks', 0),
(76, 'Life Hack #1510: Eargasm', 'http://1000lifehacks.com/post/91200628333', 'http://31.media.tumblr.com/44a6695c2945aa70ef79265c3fcc6393/tumblr_n8env7ALcj1sa4vz3o1_500.png', 'Get the best possible sound from iTunes.', '1000LifeHacks Lifehacks', 'image', 'lifehacks', 0),
(77, 'Life Hack #1509: Runny Nose', 'http://1000lifehacks.com/post/91182255048', 'http://37.media.tumblr.com/58a5b33bab2cf3e7c42cdc95f873dbdc/tumblr_n8entkGiFu1sa4vz3o1_500.png', 'Getting rid of a runny nose.', '1000LifeHacks Lifehacks', 'image', 'lifehacks', 0),
(78, 'Life Hack #1508: Apple Store Discount', 'http://1000lifehacks.com/post/91079672076', 'http://38.media.tumblr.com/9f3a9e410c2e4aadf5bb22e9fdbb1168/tumblr_n8cr0uIvyC1sa4vz3o1_500.png', 'Buying something from Apple?', '1000LifeHacks Lifehacks', 'image', 'lifehacks', 0),
(79, 'Life Hack #1507: Gatorade', 'http://1000lifehacks.com/post/91061682899', 'http://37.media.tumblr.com/9cb445e4f426d239999ff7781d617136/tumblr_n8cqyzx0k01sa4vz3o1_500.png', 'The right time to drink Gatorade or Powerade.', '1000LifeHacks Lifehacks', 'image', 'lifehacks', 0),
(80, 'Packing A Cooler', 'http://1000lifehacks.com/post/90976832107', 'http://31.media.tumblr.com/c524e5e0675dbc46cc08550e5d4a4188/tumblr_n8avseN5K11sa4vz3o1_500.png', 'How to pack a cooler.', '1000Lifehacks Lifehacks', 'image', 'lifehacks', 0),
(81, 'Life Hack #1505: Zoo Colors', 'http://1000lifehacks.com/post/90959012544', 'http://38.media.tumblr.com/5a82cacaa1888e0d60ea32cc490a8dca/tumblr_n8avrbQ4iU1sa4vz3o1_500.png', 'Wear the right colors when you go to the zoo.', '1000LifeHacks Lifehacks', 'image', 'lifehacks', 0),
(82, 'Arduino Lesson 0. Getting Started', 'https://learn.adafruit.com/lesson-0-getting-started', 'https://learn.adafruit.com/system/assets/assets/000/004/407/medium800/learn_arduino_1277_LRG.jpg?1396812020', 'In this lesson, you will learn how to setup your computer to use Arduino and how to set about the lessons that follow.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(83, 'Arduino Lesson 1. Blink', 'https://learn.adafruit.com/adafruit-arduino-lesson-1-blink', 'https://learn.adafruit.com/system/assets/assets/000/002/141/medium800/learn_arduino_overview.png?1396779914', 'In this lesson, you will learn how program your Arduino to make the Arduino''s built-in LED blink.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(84, 'Arduino Lesson 2. LEDs', 'https://learn.adafruit.com/adafruit-arduino-lesson-2-leds', 'https://learn.adafruit.com/system/assets/assets/000/002/158/medium800/learn_arduino_overview.jpg?1396780031', 'In this lesson, you will learn how to change the brightness of an LED by using different values of resistor.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(85, 'Arduino Lesson 3. RGB LEDs', 'https://learn.adafruit.com/adafruit-arduino-lesson-3-rgb-leds', 'https://learn.adafruit.com/system/assets/assets/000/002/083/medium800/learn_arduino_project_3_on_breadboard.jpg?1396779133', 'In this lesson, you will learn how to use a RGB LED with an Arduino.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(86, 'Arduino Lesson 4. Eight LEDs and a Shift Register', 'https://learn.adafruit.com/adafruit-arduino-lesson-4-eight-leds', 'https://learn.adafruit.com/system/assets/assets/000/002/101/medium800/learn_arduino_breadboard.jpg?1396779268', 'In this lesson, you will learn how to use eight LEDs using the 74HC595 shift register chip.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(87, 'Arduino Lesson 5. The Serial Monitor', 'https://learn.adafruit.com/adafruit-arduino-lesson-5-the-serial-monitor', 'https://learn.adafruit.com/system/assets/assets/000/002/178/medium800/learn_arduino_summary.png?1396780242', 'In this lesson, you will build on lesson 4, adding the facility to control the LEDs from your computer using the Arduino Serial Monitor.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(88, 'Arduino Lesson 6. Digital Inputs', 'https://learn.adafruit.com/adafruit-arduino-lesson-6-digital-inputs', 'https://learn.adafruit.com/system/assets/assets/000/002/202/medium800/learn_arduino_overview.jpg?1396780417', 'In this lesson, you will learn to use push buttons with digital inputs to turn an LED on and off.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(89, 'Arduino Lesson 7. Make an RGB LED Fader', 'https://learn.adafruit.com/adafruit-arduino-lesson-7-make-an-rgb-led-fader', 'https://learn.adafruit.com/system/assets/assets/000/002/224/medium800/learn_arduino_overview.jpg?1396780637', 'In this lesson, you will be combining some of the things that you learnt in earlier lessons to use three push switches (from lesson 6) to control the color', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(90, 'Arduino Lesson 8. Analog Inputs', 'https://learn.adafruit.com/adafruit-arduino-lesson-8-analog-inputs', 'https://learn.adafruit.com/system/assets/assets/000/002/240/medium800/learn_arduino_overview.jpg?1396780856', 'In this lesson, you will start by using the Serial Monitor to display analog readings, and then extend the project using eight LEDs from lesson 4.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(91, 'Arduino Lesson 9. Sensing Light', 'https://learn.adafruit.com/adafruit-arduino-lesson-9-sensing-light', 'https://learn.adafruit.com/system/assets/assets/000/002/273/medium800/learn_arduino_overview.jpg?1396781232', 'In this lesson, you will learn how to measure light intensity using an Analog Input.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(92, 'Arduino Lesson 10. Making Sounds', 'https://learn.adafruit.com/adafruit-arduino-lesson-10-making-sounds', 'https://learn.adafruit.com/system/assets/assets/000/002/293/medium800/learn_arduino_overview.jpg?1396781409', 'In this lesson, you will learn how to make sounds with your Arduino.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(93, 'Arduino Lesson 11. LCD Displays - Part 1', 'https://learn.adafruit.com/adafruit-arduino-lesson-11-lcd-displays-1', 'https://learn.adafruit.com/system/assets/assets/000/002/357/medium800/learn_arduino_overview.jpg?1396782223', 'In this lesson, you will learn how to wire up and use an alphanumeric LCD display.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(94, 'Arduino Lesson 12. LCD Displays - Part 2', 'https://learn.adafruit.com/adafruit-arduino-lesson-12-lcd-displays-part-2', 'https://learn.adafruit.com/system/assets/assets/000/002/442/medium800/learn_arduino_overview.jpg?1396783197', 'In this lesson, you will build on what we have learnt in lesson 11 and use a LCD display to show the temperature and light intensity.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(95, 'Arduino Lesson 13. DC Motors', 'https://learn.adafruit.com/adafruit-arduino-lesson-13-dc-motors', 'https://learn.adafruit.com/system/assets/assets/000/002/338/medium800/learn_arduino_overview.jpg?1396782013', 'In this lesson, you will learn how to control a small DC motor using an Arduino and a transistor.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(96, 'Arduino Lesson 14. Servo Motors', 'https://learn.adafruit.com/adafruit-arduino-lesson-14-servo-motors', 'https://learn.adafruit.com/system/assets/assets/000/002/304/medium800/learn_arduino_knob.jpg?1396781531', 'In this lesson, you will learn how to control a servo motor using an Arduino.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(97, 'Arduino Lesson 15. DC Motor Reversing', 'https://learn.adafruit.com/adafruit-arduino-lesson-15-dc-motor-reversing', 'https://learn.adafruit.com/system/assets/assets/000/002/473/medium800/learn_arduino_overview.jpg?1396783483', 'In this lesson, you will learn how to control both the direction and speed of a small DC motor using an Arduino and the L293D motor driver chip.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(98, 'Arduino Lesson 16. Stepper Motors', 'https://learn.adafruit.com/adafruit-arduino-lesson-16-stepper-motors', 'https://learn.adafruit.com/system/assets/assets/000/002/489/medium800/learn_arduino_overview.jpg?1396783705', 'In this lesson you will learn how to control a stepper motor using your Arduino and the same L293D motor control chip that you used with the DC motor...', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(99, 'Arduino Lesson 17. Email Sending Movement Detector', 'https://learn.adafruit.com/arduino-lesson-17-email-sending-movement-detector', 'https://learn.adafruit.com/system/assets/assets/000/004/535/medium800/learn_arduino_overview.jpg?1396814047', 'In this lesson you will learn how to use a PIR movement detector with an Arduino and to have the Arduino communicate...', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(100, 'All About Arduino Libraries', 'https://learn.adafruit.com/adafruit-all-about-arduino-libraries-install-use', 'https://learn.adafruit.com/system/assets/assets/000/004/007/medium800/learn_arduino_Books.jpg?1396807546', 'How to install and use Arduino Libraries.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(101, 'Set up and Blink - Simulink with Arduino', 'https://learn.adafruit.com/how-to-use-simulink-with-arduino', 'https://learn.adafruit.com/system/assets/assets/000/013/632/medium800/learn_arduino_TutorialModel.png?1389738735', 'How to use Simulink to program your Arduino.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(102, 'Memories of an Arduino', 'https://learn.adafruit.com/memories-of-an-arduino', 'https://learn.adafruit.com/system/guides/images/000/000/342/medium800/Stack_Operation.gif?1396718650', 'How to get the most from your Arduino Memory. You know you have a memory problem when...', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(103, 'Adafruit Arduino Selection Guide', 'https://learn.adafruit.com/adafruit-arduino-selection-guide', 'https://learn.adafruit.com/system/assets/assets/000/006/309/medium800/learn_arduino_2013_03_21_IMG_1404-1024.jpg?1396834770', 'There are many different Arduino and Arduino Compatible microcontroller boards. Which one is right for your needs?', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(104, 'Adafruit Proto Shield for Arduino', 'https://learn.adafruit.com/adafruit-proto-shield-arduino', 'https://learn.adafruit.com/system/assets/assets/000/004/455/medium800/learn_arduino_1341944959_d39a197f27_b.jpg?1396813329', 'This is a design for an open-source prototyping shield for Arduino NG/Diecimila. It has tons of cool features, to make prototyping on your Arduino easy.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(105, 'Arduino Tips, Tricks, and Techniques', 'https://learn.adafruit.com/arduino-tips-tricks-and-techniques', 'https://learn.adafruit.com/system/assets/assets/000/003/199/medium800/learn_arduino_arduinounotop.jpg?1396793561', 'There''s so many Arduino''s out there, it may get a little confusing. We wanted to clarify for people some of the changes in the latest version.', 'Adafruit Arduino Maker', 'text', 'maker', 0),
(106, 'Why Should I Invest?', 'http://www.fool.com/investing/beginning/why-should-i-invest.aspx?source=iibedihpo0000001', 'img/3.jpg', 'Welcome to Investing Basics! If you''ve found your way here, chances are you''ve either got some money socked away or you''re planning to do so.', 'TheMotleyFool Money Invest', 'text', 'money', 0),
(107, '52 Ways to Save $100: Week #1: Bake Your Own Bread', 'http://moneysavingmom.com/2013/01/52-different-ways-to-save-at-least-100-this-year-bake-your-own-bread-week-1.html', 'http://cdn1.moneysavingmom.com/wp-content/uploads/2013/01/7367123706_6a6135bd4c.jpg', 'You can save over $100 per year by making your own homemade bread!', 'MoneySavingMom Money Save', 'text', 'money', 0),
(108, '52 Ways to Save $100: Week #2: Make Your Own Coffee at Home', 'http://moneysavingmom.com/2013/01/52-ways-to-save-at-least-100-this-year-make-your-own-coffee-at-home-week-2-2.html', 'http://cdn1.moneysavingmom.com/wp-content/uploads/2013/01/8382182534_97d95602a8.jpg', 'Relax! You Don&#39;t Have to Give Up the Coffeeshop Habit Completely!', 'MoneySavingMom Money Save', 'text', 'money', 0),
(109, '52 Ways to Save $100: Week #3: Ditch Your Cable Package', 'http://moneysavingmom.com/2013/01/52-different-ways-to-save-100-this-year-ditch-your-cable-package-week-3.html', 'http://cdn2.moneysavingmom.com/wp-content/uploads/2013/01/Is-It-Possible-to-Survive-Without-Cable-TV-600x394.jpg', 'You knew it was coming... Yup, were talking about ditching cable TV this week.', 'MoneySavingMom Money Save', 'text', 'money', 0),
(110, '52 Ways to Save $100: Week #4: Order Prescription Glasses Online', 'http://moneysavingmom.com/2013/01/52-different-ways-to-save-100-per-year-order-prescription-lenses-online-week-4.html', 'http://cdn1.moneysavingmom.com/wp-content/uploads/2013/01/How-to-Save-Hundreds-of-Dollars-By-Ordering-Prescription-Glasses-Online.jpg', 'For those of you who need to buy glasses or who end up needing to buy glasses, this tip will save you $100+ this year.', 'MoneySavingMom Money Save', 'text', 'money', 0),
(111, '52 Ways to Save $100: Week #5: Make Your Own Homemade Cleaners', 'http://moneysavingmom.com/2013/02/52-different-ways-to-save-100-per-year-make-your-own-homemade-cleaners-week-5.html', 'http://cdn2.moneysavingmom.com/wp-content/uploads/2013/02/8031549313_e509eebe42.jpg', 'We don&#39;t even consider an alternative to paying for what we normally buy. Homemade cleaners are one such example.', 'MoneySavingMom Money Save', 'text', 'money', 0),
(112, '52 Ways to Save $100: Week #6: Make Your Own Homemade Mixes', 'http://moneysavingmom.com/2013/02/52-different-ways-to-save-100-per-year-make-your-own-homemade-mixes-week-6.html', 'http://cdn2.moneysavingmom.com/wp-content/uploads/2013/02/Make-Your-Own-Homemade-Mixes-red.jpg', 'The majority of families who don&#39;t cook and bake completely from scratch would likely save at least $8&dash;$10 per month by making their own mixes.', 'MoneySavingMom Money Save', 'text', 'money', 0),
(113, '52 Ways to Save $100: Week #7: Become A One Car Family', 'http://moneysavingmom.com/2013/02/52-different-ways-to-save-100-per-year-become-a-one-car-family-week-7.html', 'http://cdn2.moneysavingmom.com/wp-content/uploads/2013/02/How-We-Saved-1500-a-Year-By-Becoming-a-One-Car-Family.jpg', 'Think how much you&#039;d save in gas if you dropped one of your cars and carpooled, used public transportation, road your bike, or just stayed home more.', 'MoneySavingMom Money Save', 'text', 'money', 0),
(114, 'LeBron James Signature Moves: Between The Legs Hesitation Dribble', 'https://www.youtube.com/watch?v=7cz3HnCgr80', 'https://i1.ytimg.com/vi_webp/7cz3HnCgr80/mqdefault.webp', 'Watch and learn as LeBron James teaches the between the legs hesitation dribble, which allows you to explode past the defense.', 'Nike Basketball Sports LBJ', 'video', 'sports', 0),
(115, 'Signature Moves: LeBron James - Fake & Pass', 'https://www.youtube.com/watch?v=BORHmNaSJeM', 'https://i1.ytimg.com/vi/BORHmNaSJeM/mqdefault.jpg', 'You''re a threat from all over the court, so the defense is looking to keep you from scoring. Use that threat to create opportunities for your teammates.', 'Nike Basketball Sports LBJ', 'video', 'sports', 0),
(116, 'LeBron James Signature Moves: Between The Legs Step Back', 'https://www.youtube.com/watch?v=89Z-yw_UiMw', 'https://i1.ytimg.com/vi_webp/89Z-yw_UiMw/mqdefault.webp', 'LeBron James walks us through his between the legs step back. Watch how he breaks down the defense with his signature move.', 'Nike Basketball Sports LBJ', 'video', 'sports', 0),
(117, 'Nike Basketball Signature Moves: Russell Westbrook''s Treadmill', 'http://www.youtube.com/watch?v=ZXMDnJzPv8A', 'http://i1.ytimg.com/vi_webp/ZXMDnJzPv8A/mqdefault.webp', 'Add Russell Westbrook''s Treadmill to your arsenal on the court with Nike Basketball''s Signature Moves. Take Every Advantage.', 'Nike Basketball Sports', 'video', 'sports', 0),
(118, 'Nike Basketball Signature Moves: Russell Westbrook''s Shake & Bake', 'http://www.youtube.com/watch?v=xVu57BpAMAM', 'http://i1.ytimg.com/vi_webp/xVu57BpAMAM/mqdefault.webp', 'Add Russell Westbrook''s Shake and Bake to your arsenal on the court with Nike Basketball''s Signature Moves.', 'Nike Basketball Sports', 'video', 'sports', 0),
(119, 'Nike Pro Answers | Kyrie Irving | The Ball Spin', 'http://www.youtube.com/watch?v=XKOeu8n7R7s', 'http://i1.ytimg.com/vi/XKOeu8n7R7s/mqdefault.jpg', 'Kyrie Irving shares how he uses spin to score. Increase your knowledge and raise your game with Nike Pro Answers: htt', 'Nike Basketball Sports', 'video', 'sports', 0),
(120, 'Nike Basketball Pro Training, Andre Iguodala, Defense: Zig Zags', 'http://www.youtube.com/watch?v=nNz4hWDrxJw', 'http://i1.ytimg.com/vi_webp/nNz4hWDrxJw/mqdefault.webp', 'Everything from the correct technique for closing out to using your lateral quickness on defensive slides.', 'Nike Basketball Sports', 'video', 'sports', 0),
(121, 'Nike Academy: Off-Season Training', 'http://www.youtube.com/watch?v=hdOscBSWZ8c', 'http://i1.ytimg.com/vi/hdOscBSWZ8c/mqdefault.jpg', 'Pros can''t afford to take the whole summer off. Get ready for pre-season with these drills.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(122, 'Nike Academy: Direct Free Kicks', 'http://www.youtube.com/watch?v=TFQAur1y9WM', 'http://i1.ytimg.com/vi/TFQAur1y9WM/mqdefault.jpg', 'Big games can be decided by set pieces. The best free kick takers practice relentlessly, hone their technique and can hit a variety of free kicks.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(123, 'Nike Academy: Crossing & Finishing', 'http://www.youtube.com/watch?v=ljZJVvZZKCw', 'http://i1.ytimg.com/vi/ljZJVvZZKCw/mqdefault.jpg', 'Prolific scorers perfect their craft every day. This is how the Nike Academy work on converting crosses.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(124, 'Nike Academy: Defending: Body Position', 'http://www.youtube.com/watch?v=ZqDfqIDid8I', 'http://i1.ytimg.com/vi/ZqDfqIDid8I/mqdefault.jpg', 'Even at top level, defenders get body position wrong. Use these drills to correct yours.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(125, 'Nike Academy: Shot Stopping', 'http://www.youtube.com/watch?v=aOvEr_vb5yg', 'http://i1.ytimg.com/vi/aOvEr_vb5yg/mqdefault.jpg', 'Stop anything that comes your way. This is how Nike Academy keepers prepare for matches.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(126, 'Nike Academy: Keep in Shape over Holidays', 'http://www.youtube.com/watch?v=RCjKtIwPOUs', 'http://i1.ytimg.com/vi/RCjKtIwPOUs/mqdefault.jpg', 'Make the Christmas break work for you. These Nike Academy drills and guides to nutrition will help keep you in shape and on your game.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(127, 'Nike Academy: Indirect Free Kicks', 'http://www.youtube.com/watch?v=axABdrkzS4k', 'http://i1.ytimg.com/vi/axABdrkzS4k/mqdefault.jpg', 'Set pieces can be deadly. Use disguise and variety to surprise the keeper and catch the defense off guard. Here''s how to make set pieces count.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(128, 'Nike Academy: Power Up', 'http://www.youtube.com/watch?v=iARvobeY2Jo', 'http://i1.ytimg.com/vi_webp/iARvobeY2Jo/mqdefault.webp', 'Nike Chance winner, Ukrainian Eldar Bodrov, needs to increase his power and speed to impress pro clubs. Watch his power workout with coach Chris Thorpe.', 'NIke Academy Football Soccer', 'video', 'sports', 0),
(129, 'Nike Academy: Improve Your Speed', 'http://www.youtube.com/watch?v=-6sghWdstOo', 'http://i1.ytimg.com/vi/-6sghWdstOo/mqdefault.jpg', 'Technique is key to speed. Watch Nike Chance winner Eldar Bodrov become faster with coach Chris Thorpe.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(130, 'Nike Academy: Defending: Staying Compact', 'http://www.youtube.com/watch?v=D72gPqw3ILA', 'http://i1.ytimg.com/vi/D72gPqw3ILA/mqdefault.jpg', 'A tight defensive unit forces the opponents out to the wings. Here''s how to do it.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(131, 'Nike Academy: Winter Training', 'http://www.youtube.com/watch?v=n527EgDB5tI', 'http://i1.ytimg.com/vi_webp/n527EgDB5tI/mqdefault.webp', 'This is how Nike Academy players defeat winter temperatures, maintaining high performance in any conditions. http://go.nike.com/ProCombatEU', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(132, 'Nike Academy: Adapt your game', 'http://www.youtube.com/watch?v=YBG55Hx8ezI', 'http://i1.ytimg.com/vi/YBG55Hx8ezI/mqdefault.jpg', 'The best players can perform in any formation. Here''s how we work on adaptability.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(133, 'Nike Academy: Comeback From Injury', 'http://www.youtube.com/watch?v=cE0_vr-QRdk', 'http://i1.ytimg.com/vi_webp/cE0_vr-QRdk/mqdefault.webp', 'With the right rehab and mentality, you can come back as strong as before.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(134, 'Nike Academy: Defending Checklist', 'http://www.youtube.com/watch?v=6K1pum718b8', 'http://i1.ytimg.com/vi/6K1pum718b8/mqdefault.jpg', 'Stop conceding goals. Break defending down to four elements.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(135, 'Nike Academy Building Stamina', 'http://www.youtube.com/watch?v=wfR2KGB1amM', 'http://i1.ytimg.com/vi/wfR2KGB1amM/mqdefault.jpg', 'Nike Academy Building Stamina', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(136, 'Nike Academy Tactics: Playing from the back', 'http://www.youtube.com/watch?v=MdtOq_XlZAU', 'http://i1.ytimg.com/vi_webp/MdtOq_XlZAU/mqdefault.webp', 'The back four set the pace of the game. Assistant coach Matt Wells shows how the Nike Academy play out from the back to dominate possession.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(137, 'Nike Academy: Match Preparation and Recovery', 'http://www.youtube.com/watch?v=pGTmeKdALD8', 'http://i1.ytimg.com/vi_webp/pGTmeKdALD8/mqdefault.webp', 'How to succeed in your first league game? Spot-on pre-match training, the right nutrition and recovery are all vital.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(138, 'Nike Academy: Tactics: Making Goalkeepers Kick', 'http://www.youtube.com/watch?v=jIAG8dWDMOI', 'http://i1.ytimg.com/vi_webp/jIAG8dWDMOI/mqdefault.webp', 'It''s important to stop a good team from playing out. How will the Nike Academy put their opposition under pressure this week?', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(139, 'Nike Academy: Physio Clinic: Ankle Injuries', 'http://www.youtube.com/watch?v=U6CmqAd5t7I', 'http://i1.ytimg.com/vi_webp/U6CmqAd5t7I/mqdefault.webp', 'Ryan Tinsley''s been out with a broken metatarsal since October. Watch Glyn take him through key rehab exercises.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(140, 'Nike Academy 2010/11: Dealing with Disappointment', 'http://www.youtube.com/watch?v=AGte3OoD1x4', 'http://i1.ytimg.com/vi_webp/AGte3OoD1x4/mqdefault.webp', 'All footballers suffer disappointments. The great ones use it to fire them up and come back stronger. See what advice Rio Ferdinand and Huw Jennings give.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(141, 'Nike Academy: Physio Clinic: Knee Injuries', 'http://www.youtube.com/watch?v=K0pC6c7cnpU', 'http://i1.ytimg.com/vi_webp/K0pC6c7cnpU/mqdefault.webp', 'Knee injuries are extremely common in football. The right rehab is key. The Nike Academy''s physio Glyn Davies works with defender Lewis Tallack.', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(142, 'Nike Academy - Physical Conditioning', 'http://www.youtube.com/watch?v=jf-snv5_WNo', 'http://i1.ytimg.com/vi_webp/jf-snv5_WNo/mqdefault.webp', 'Jon Goodman has stepped in to put the lads through their paces working on drills to increase endurance, improve reaction speed and boo', 'Nike Academy Football Soccer', 'video', 'sports', 0),
(143, 'Nike Football Skills: Calvin Johnson''s Pro Move', 'http://www.youtube.com/watch?v=Qf54vWyYonk', 'http://i1.ytimg.com/vi_webp/Qf54vWyYonk/mqdefault.webp', 'Running the proper routes takes discipline and technique. Here Calvin Johnson demonstrates how to run the perfect fade route.', 'USNikeFootball Football', 'video', 'sports', 0),
(144, 'Nike Football Skills: Adrian Peterson''s Pro Move', 'http://www.youtube.com/watch?v=hQW7ussbT3I', 'http://i1.ytimg.com/vi/hQW7ussbT3I/mqdefault.jpg', 'Yards-per-carry means everything to a running back. Take a look at how Adrian Peterson gets those extra yards after contact and keeps those chains moving.', 'USNikeFootball Football', 'video', 'sports', 0),
(145, 'Nike Football Skills: Nmadi Asomughas Pro Move', 'http://www.youtube.com/watch?v=fEDV78kVyb8', 'http://i1.ytimg.com/vi/fEDV78kVyb8/mqdefault.jpg', 'Playing off coverage as a defensive back is a lot of pressure. Follow Nmadi Asomugha, step-by-step, as he explains.', 'USNikeFootball Football', 'video', 'sports', 0);
INSERT INTO `post` (`ID`, `title`, `link`, `image`, `description`, `tags`, `type`, `category`, `clicks`) VALUES
(146, 'Nike Pro Answers | LeBron James | The Chase Down Block', 'http://www.youtube.com/watch?v=fiaM0LC2SM8', 'http://i1.ytimg.com/vi/fiaM0LC2SM8/mqdefault.jpg', 'LeBron james describes how to execute his signature chase down block.', 'Nike Basketball Sports LBJ', 'video', 'sports', 0),
(147, 'Nike Pro Answers | Ty Lawson | The Hesitation Dribble', 'http://www.youtube.com/watch?v=ftVUTICS1uM', 'http://i1.ytimg.com/vi/ftVUTICS1uM/mqdefault.jpg', 'Ty Lawson uses the hesitation dribble to keep the defense guessing. Increase your knowledge and raise your game with Nike Pro Answers.', 'Nike Basketball Sports', 'video', 'sports', 0),
(148, 'Why Founders Fail: The Product CEO Paradox', 'http://www.bhorowitz.com/why_founders_fail_the_product_ceo_paradox', 'img/3.jpg', 'There are three main reasons why founders fail to run the companies they created.', 'BenHorowitz BensBlog Startups', 'text', 'startups', 0),
(149, 'There&#039;s only a few ways to scale user growth', 'http://andrewchen.co/2014/07/08/theres-only-a-few-ways-to-scale-user-growth-and-heres-the-list/', 'http://1g1uem2nc4jy1gzhn943ro0gz50.wpengine.netdna-cdn.com/wp-content/uploads/2014/07/MP900433069.jpg', 'Here are the major channels that successful products use to drive traction &dash; think of them as the moonshots.', 'AndrewChen Startups Growth', 'text', 'startups', 0),
(150, 'How to solve the cold-start problem for social products', 'http://andrewchen.co/2014/03/27/how-to-solve-the-cold-start-problem-for-social-products/', 'http://1g1uem2nc4jy1gzhn943ro0gz50.wpengine.netdna-cdn.com/wp-content/uploads/2014/03/EmptySeats-m.jpg', 'Here&#039;s a few ways I&#039;ve collected over time on how to approach that problem.', 'AndrewChen Startups Social', 'text', 'startups', 0),
(151, 'How to design successful social products with 3 feedback loops', 'http://andrewchen.co/2014/03/17/how-to-design-successful-social-products-with-3-habit-forming-feedback-loops/', 'http://1g1uem2nc4jy1gzhn943ro0gz50.wpengine.netdna-cdn.com/wp-content/uploads/2014/03/TOMA_3loopsW2.jpg', 'I&#039;ve come to believe there&#039;s 3 main feedback loops that drive the success of these social product designs: here&#039;s the trifecta.', 'AndrewChen Startups Feedback', 'text', 'startups', 0),
(152, 'Can Do vs. Can&#039;t Do Cultures', 'http://www.bhorowitz.com/can_do_vs_cant_do_cultures', 'img/3.jpg', 'Some people would like to turn the technology startup world into one great big company with a degenerative Can&#039;t Do Culture.', 'BenHorowitz BensBlog Startups', 'text', 'startups', 0),
(153, 'Cash Flow and Destiny', 'http://www.bhorowitz.com/cash_flow_and_destiny', 'img/3.jpg', 'If you are an entrepreneur, you have probably heard some crusty old CEO or investor say something like:cash is king.', 'BenHorowitz BensBlog Startups', 'text', 'startups', 0),
(154, 'Revenge of the Fat Guy', 'http://www.bhorowitz.com/revenge_of_the_fat_guy', 'img/3.jpg', 'Entrepreneurs should build the product that everybody wants before raising a boatload of cash to build the company.', 'BenHorowitz BensBlog Startups', 'text', 'startups', 0),
(155, 'How to overcome the startup growth plateau', 'http://insideintercom.io/how-to-overcome-the-startup-growth-plateau/', 'http://insideintercom.io/wp-content/uploads/2014/07/Cloudsponge-chart_740-1.jpg', 'Jay Gibb, founder of CloudSponge, explains how he used highly-targeted emails to nurture relationships with new and existing customers.', 'InsideIntercom Startups Growth', 'text', 'startups', 0),
(156, 'Defining Static Web Apps', 'http://www.staticapps.org/articles/defining-static-web-apps', 'img/3.jpg', 'A Static Web Application is any web application that can be delivered directly to an end user''s browser without any server-side alteration of the HTML, CSS', 'Tech Web Dev Static Apps', 'text', 'tech', 0),
(157, 'Why Build Static Web Apps?', 'http://www.staticapps.org/articles/why-build-static-apps', 'img/3.jpg', 'Rather than assemble content in server-side processes, static web applications rely on the user''s browser to drive interaction and content rendering.', 'Tech Web Dev Static Apps', 'text', 'tech', 0),
(158, 'Thinking With Services for Static Web Apps', 'http://www.staticapps.org/articles/thinking-with-services', 'img/3.jpg', 'Building an application with service orientation comes with three key benefits.', 'Tech Dev Static Apps', 'text', 'tech', 0),
(159, 'Assembling Your Static App Stack', 'http://www.staticapps.org/articles/assembling-your-static-app-stack', 'img/3.jpg', 'Once you&#039ve decided to build a static web application, there are still several important choices to be made in terms of your app&#039;s tech stack.', 'Tech Web Dev Static Apps', 'text', 'tech', 0),
(160, 'Routing URLs in Static Web Apps', 'http://www.staticapps.org/articles/routing-urls-in-static-apps', 'img/3.jpg', 'So how can we maintain clean, readable URLs while still doing the heavy lifting in the browser?', 'Tech Web Dev Static Apps', 'text', 'tech', 0),
(161, 'Authentication and Authorization', 'http://www.staticapps.org/articles/authentication-and-authorization', 'img/3.jpg', 'Authentication is perhaps the single most common requirement of any application.', 'Tech Web Dev Static Apps', 'text', 'tech', 0),
(162, 'Cross-Domain Requests with CORS', 'http://www.staticapps.org/articles/cross-domain-requests-with-cors', 'img/3.jpg', 'Cross-Origin Resource Sharing CORS is a powerful technology for static web apps.', 'Tech Web Dev Static Apps', 'text', 'tech', 0),
(163, 'Front&dash;End Error Handling', 'http://www.staticapps.org/articles/front-end-error-handling', 'img/3.jpg', 'Error handling is a vital part of any app&#039;s user experience, and if done well, can leave your users feeling informed and properly considered.', 'Tech Web Dev Static Apps', 'text', 'tech', 0),
(164, 'Protecting Static Apps from CSRF and XSS', 'http://www.staticapps.org/articles/csrf-and-xss-on-static-apps', 'img/3.jpg', 'if you are building back&dash;end services to go with your application you still very much need to protect your app.', 'Tech Web Dev Static Apps', 'text', 'tech', 0),
(165, 'Access The Deep Web On Your Mac', 'http://www.macinfo.us/how-to-access-the-deepweb-on-your-mac.php', 'http://www.macinfo.us/resources/Screen%20Shot%202013-01-29%20at%209.38.53%20PM.jpg', 'This article is designed specifically for Mac users who want to use & stay safe on the Deep Web.', 'MacInfoUS Tech Deep Web', 'text', 'tech', 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
